### PR TITLE
Adds Jump Menu plugin to Ckeditor5

### LINKED ISSUE #74: CK5 Plugin : Jump Menu Creator
We need to come up with some implementation to create jump menus for content within a node based on DOM elements.  (e.g. jump to all H2 tags on the page).  

Should try to use the D7 implementation as a guide and @kevincrafts will add in comments.

### PR DESCRIPTION
**Pull request by patrickbrown-io**
### Jump Menu Button
Adds a 'Jump Menu' CKEditor 5 plugin to the Editor toolbar. On insertion, this insets a Jump Menu web component that allows automatic jump menu creation and link creation to any specified header tags on the page. You may also customize the title of your Jump Menu.

Includes:
- `profile` =>  https://github.com/CuBoulder/tiamat10-profile/pull/168
- `ucb_ckeditor_plugins` => https://github.com/CuBoulder/ucb_ckeditor_plugins/pull/87

Resolves #74

### CODE REVIEW

**Comment by timurtripp** [comment]
- "Articles by Rux Rux" is in a hidden section of the page and should not be appearing here. I did a quick search and there is a way to detect if an element (or one of its parents) is hidden via JavaScript. Screenshot 2024-07-19 at 3 37 27 PM
- Use hyphenation between words when assigning ids to the header tags.

**Review by jnicholCU — APPROVED** [review]
Very clean. Works well. Runs as expected. 10/10

**Review by jnicholCU — CHANGES_REQUESTED** [review]
In layout builder, a block with a jumpmenu is draggable, but it doesn't actually move and can't be place somewhere else.
Other items can be dragged around it.

Specifically the console throws this error 
`Uncaught TypeError: Cannot read properties of undefined (reading 'nodeType')`

image

**Review by jnicholCU — APPROVED** [review]

**Review by timurtripp — CHANGES_REQUESTED** [review]
Getting errors whenever I click the web component inside the widget.

**Pull request merged**
