### PR TITLE
Change: Button Groups - 'Add Button' Functionality & UI Enhancements

### LINKED ISSUE #29: Adding buttons to button groups
There should be an easier way to add buttons to button groups after creation time, potentially by adding an "Add" option to the UI balloon.

Also might suggest converting this to a widget toolbar with instant apply of changes rather than requiring confirmation, similar to how some of our other widgets like Box and Icon work. This could behave very similarly to Box where the toolbar appears after the insert of the widget allowing for the needed customization.

A widget toolbar looks like this and does not have confirm or cancel buttons.
Screen Shot 2023-09-14 at 10 23 08 AM

### PR DESCRIPTION
**Pull request by patrickbrown-io**
New Changes to the Button Group plugin includes the following enhancements:

- Ability to add new Buttons to existing Button Groups by selecting the new `+` icon on the Button Group Toolbar. Editors can now create an empty Button Group first and then add Buttons to it, as well as adding new Buttons to an existing Button Group. Editors may still select existing Buttons and then create the Button Group. 

- Button Group's UI no longer requires confirmation of changes. Selection of Button Group color and size are instantly applied using the Button Group Toolbar. 

Resolves #29

### CODE REVIEW

**Comment by timurtripp** [comment]
Great work! The only lingering issues are it displays differently in the editor
Screen Shot 2023-09-25 at 3 20 02 PM
vs. outside the editor
Screen Shot 2023-09-25 at 3 18 50 PM
and this ghost toolbar issue
Screen Shot 2023-09-25 at 3 20 11 PM
 otherwise it works great!

**Comment by timurtripp** [comment]
✅ Ghost toolbar – fixed
✅ Different display in editor and page – fixed

Button focus on insert:
It is indeed focused but doesn't bring up the UI for me to immediately paste the URL for the button. Strange.

**Review by timurtripp — CHANGES_REQUESTED** [review]
A bug was found with the toolbar if one of the buttons is selected. Requesting changes.

**Review by jcsparks — APPROVED** [review]

**Comment by jcsparks** [comment]
Really good enhancement @patrickbrown-io  - we'll capture any additional updates or enhancements in future tickets.

**Pull request merged**
